params:
  device: cuda:0
  category: bottle
  height: 256
  width: 256
  tracking_uri: databricks
  experiment_name: /Users/inoue@nablas.com/sandbox
  run_name: PaDiM_${params.category}

model:
  name: padim.models - WideResNet50
  args:

transform:
  train:
    - name: albumentations - Resize
      args:
        height: ${params.height}
        width: ${params.width}
        p: 1
    - name: albumentations - Normalize
      args:
        mean: ${params.normalize_mean}
        std: ${params.normalize_std}
        p: 1
    - name: albumentations.pytorch - ToTensorV2
      args:
        p: 1
  test:
    - name: albumentations - Resize
      args:
        height: ${params.height}
        width: ${params.width}
        p: 1
    - name: albumentations - Normalize
      args:
        mean: ${params.normalize_mean}
        std: ${params.normalize_std}
        p: 1
    - name: albumentations.pytorch - ToTensorV2
      args:
        p: 1

dataset:
  train:
    name: mvtec.datasets - MVTecDataset
    args:
      data_dir: /data
      data_type: train
      category: ${params.category}
  test:
    name: mvtec.datasets - MVTecDataset
    args:
      data_dir: /data
      data_type: test
      category: ${params.category}

dataloader:
  train:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.train_batch_size}
      num_workers: ${params.train_batch_size}
      pin_memory: true
      shuffle: true
  test:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.test_batch_size}
      num_workers: ${params.test_batch_size}
      pin_memory: true
      shuffle: true

